import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from '../components/sidebar';
import "./globals.css";
import { getSession } from "@/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
           <Sidebar />
           <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
